// Piano Highway visualization plugin — Synthesia-style scrolling
// piano renderer with MIDI keyboard input, WebAudioFont synthesizer,
// and accuracy scoring.
//
// Wave B migration (slopsmith#36): the plugin used to wrap
// window.playSong and toggle itself on/off based on arrangement name.
// That activation model has been replaced by slopsmith core's viz
// picker + Auto mode. This file now exports a setRenderer factory at
// window.slopsmithViz_piano and declares matchesArrangement so Auto
// mode picks piano automatically on Keys / Piano / Synth arrangements.
//
// Single-instance assumption: the plugin currently keeps overlay
// canvas, scoring state, and the settings panel at module scope. The
// main-player viz picker constructs at most one instance at a time,
// so this is correct today. Splitscreen's per-panel setRenderer
// adoption (Wave C) will re-factor these into createFactory closures
// so multiple panes can host independent piano instances.

(function () {
'use strict';

// ═══════════════════════════════════════════════════════════════════════
// Config
// ═══════════════════════════════════════════════════════════════════════

// Word-boundary match so unrelated arrangement names don't trigger
// Auto-piano via a substring hit — "Monkeys" must NOT match "keys",
// "Synthesis" must NOT match "synth", etc. The \b anchors on either
// side catch standard Rocksmith arrangement labels cleanly: "Lead
// Keys", "Rhythm Piano", "Keyboard", "Synth Bass", etc.
const KEYS_PATTERNS = /\b(?:keys|piano|keyboard|synth)\b/i;
const VISIBLE_SECONDS = 3.0;
const NOW_LINE_Y_FRAC = 0.82;
const KEYBOARD_H_FRAC = 0.15;
const NOTE_LABEL_MIN_H = 16;
const HIT_TOLERANCE = 0.10;        // seconds

// ── Persisted settings ───────────────────────────────────────────────
//
// Explicit map from the in-memory property name to the localStorage
// key. The previous code read from one set of keys (e.g.
// 'piano_midi_input') and wrote to a DIFFERENT set generated by
// snake-casing the JS name ('piano_midi_input_id'), so settings
// silently evaporated on reload — the save succeeded at the wrong
// key and the next load's getItem came back empty. Centralising the
// mapping here keeps read and write symmetric.

const STORE_KEYS = {
    midiInputId:   'piano_midi_input',
    instrumentIdx: 'piano_instrument',
    synthVolume:   'piano_synth_vol',
    midiChannel:   'piano_midi_ch',
    transpose:     'piano_transpose',
    showNoteNames: 'piano_note_names',
    hitDetection:  'piano_hit_detect',
};

const _cfg = {
    midiInputId:   localStorage.getItem(STORE_KEYS.midiInputId) || '',
    instrumentIdx: parseInt(localStorage.getItem(STORE_KEYS.instrumentIdx) || '0'),
    synthVolume:   parseFloat(localStorage.getItem(STORE_KEYS.synthVolume) || '0.7'),
    midiChannel:   parseInt(localStorage.getItem(STORE_KEYS.midiChannel) || '-1'),
    transpose:     parseInt(localStorage.getItem(STORE_KEYS.transpose) || '0'),
    showNoteNames: localStorage.getItem(STORE_KEYS.showNoteNames) !== 'false',
    hitDetection:  localStorage.getItem(STORE_KEYS.hitDetection) === 'true',
};

function _saveCfg(key, val) {
    _cfg[key] = val;
    const storeKey = STORE_KEYS[key];
    if (!storeKey) return;
    try { localStorage.setItem(storeKey, String(val)); } catch (_) {}
}

// ═══════════════════════════════════════════════════════════════════════
// Module-level singleton state
// ═══════════════════════════════════════════════════════════════════════

// ── MIDI input ────────────────────────────────────────────────────────
let _midiAccess = null;
let _midiInput = null;
// _midiActive gates onmidimessage wiring. init() flips it true and
// destroy() flips it false (before detaching). Because _midiInit is
// async, a `requestMIDIAccess()` promise begun in init() can resolve
// AFTER destroy() has already run — the resulting _midiAutoConnect
// would otherwise assign `_midiInput.onmidimessage = _midiOnMessage`
// on a renderer that's no longer visible, re-enabling synth + scoring
// in the background. Every callsite that would attach the handler
// consults _midiActive first; pause/resume are the only paths that
// flip it.
let _midiActive = false;
const _heldNotes = new Map();      // transposed midi -> velocity
let _sustainOn = false;
const _sustainedNotes = new Set();  // midi notes pending release on pedal up

// ── Synth ─────────────────────────────────────────────────────────────
let _audioCtx = null;
let _synthPlayer = null;
let _synthPreset = null;
let _synthGain = null;
const _noteEnvelopes = new Map();   // transposed midi -> envelope
let _synthLoading = false;
let _playerScriptLoaded = false;

// ── Rendering / scoring (single active instance) ──────────────────────
let _pianoCanvas = null;
let _pianoCtx = null;
let _settingsPanel = null;
let _settingsGear = null;
let _settingsVisible = false;
let _highwayCanvas = null;          // the canvas handed to init(); must restore on destroy
let _prevHighwayDisplay = '';

let _displayLo = null;
let _displayHi = null;
let _cachedLayout = null;
let _lastLayoutW = 0;
let _lastRangeLo = -1;
let _lastRangeHi = -1;

let _hits = 0, _misses = 0, _streak = 0, _bestStreak = 0;
const _hitNoteKeys = new Set();     // "time|midi" for correctly hit notes
const _wrongFlashes = [];           // [{midi, wall}] for brief red flashes
const _missedNoteKeys = new Set();  // "time|midi" for notes that passed unplayed

// Latest filtered arrays cached by draw(bundle) so async MIDI event
// handlers (_checkHit, fired on key-down) can score against the same
// difficulty-filtered chart the user is seeing. Bundle.notes/chords
// are difficulty-aware; highway.getNotes()/.getChords() are not.
let _latestNotes = null;
let _latestChords = null;
let _latestTime = 0;

// ═══════════════════════════════════════════════════════════════════════
// MIDI / Color Helpers
// ═══════════════════════════════════════════════════════════════════════

const NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];

function noteToMidi(string, fret) { return string * 24 + fret; }

function midiToNoteName(midi) {
    return NOTE_NAMES[midi % 12] + (Math.floor(midi / 12) - 1);
}

function isBlackKey(midi) {
    const pc = midi % 12;
    return pc === 1 || pc === 3 || pc === 6 || pc === 8 || pc === 10;
}

function _noteKey(time, midi) {
    return time.toFixed(3) + '|' + midi;
}

// ── Neon rainbow per chromatic note (Openthesia-style) ────────────────

const NEON_RGB = [
    [1.0, 0.2, 0.3],  // C  — Pink/Red
    [1.0, 0.4, 0.4],  // C# — Light Red
    [1.0, 0.9, 0.2],  // D  — Yellow
    [1.0, 0.8, 0.4],  // D# — Light Yellow
    [0.2, 0.8, 1.0],  // E  — Cyan/Blue
    [1.0, 0.6, 0.1],  // F  — Orange
    [1.0, 0.5, 0.3],  // F# — Light Orange
    [0.3, 1.0, 0.3],  // G  — Green
    [0.4, 1.0, 0.4],  // G# — Light Green
    [0.6, 0.3, 1.0],  // A  — Purple
    [0.7, 0.4, 1.0],  // A# — Light Purple
    [1.0, 0.3, 1.0],  // B  — Magenta
];

function _neonRGB(midi) { return NEON_RGB[midi % 12]; }

function _rgbStr(r, g, b, a) {
    return a !== undefined
        ? `rgba(${(r * 255) | 0},${(g * 255) | 0},${(b * 255) | 0},${a})`
        : `rgb(${(r * 255) | 0},${(g * 255) | 0},${(b * 255) | 0})`;
}

// ═══════════════════════════════════════════════════════════════════════
// Instruments (WebAudioFont — General MIDI via JCLive soundfont)
// ═══════════════════════════════════════════════════════════════════════

const WAF_BASE = 'https://surikov.github.io/webaudiofontdata/sound/';
const WAF_PLAYER_URL = 'https://surikov.github.io/webaudiofont/npm/dist/WebAudioFontPlayer.js';
const WAF_SF = 'JCLive_sf2_file';

const INSTRUMENTS = [
    { name: 'Grand Piano',    gm: 0  },
    { name: 'Electric Piano',  gm: 4  },
    { name: 'Honky-tonk',      gm: 3  },
    { name: 'Organ',            gm: 19 },
    { name: 'Strings',          gm: 48 },
    { name: 'Synth Lead',       gm: 80 },
    { name: 'Synth Pad',        gm: 88 },
    { name: 'Harpsichord',      gm: 6  },
    { name: 'Vibraphone',       gm: 11 },
    { name: 'Music Box',        gm: 10 },
];

function _wafFile(gm) {
    return String(gm * 10).padStart(4, '0') + '_' + WAF_SF;
}

function _wafVar(gm)  { return '_tone_' + _wafFile(gm); }
function _wafUrl(gm)  { return WAF_BASE + _wafFile(gm) + '.js'; }

// ═══════════════════════════════════════════════════════════════════════
// Script loader
// ═══════════════════════════════════════════════════════════════════════

function _loadScript(url) {
    return new Promise((resolve, reject) => {
        if (document.querySelector(`script[src="${url}"]`)) { resolve(); return; }
        const s = document.createElement('script');
        s.src = url;
        s.onload = resolve;
        s.onerror = () => reject(new Error('Failed to load ' + url));
        document.head.appendChild(s);
    });
}

// ═══════════════════════════════════════════════════════════════════════
// WebAudioFont synthesizer
// ═══════════════════════════════════════════════════════════════════════

async function _synthInit() {
    if (_synthPlayer) return;
    try {
        if (!_playerScriptLoaded) {
            await _loadScript(WAF_PLAYER_URL);
            _playerScriptLoaded = true;
        }
        if (typeof WebAudioFontPlayer === 'undefined') return;

        _audioCtx = new (window.AudioContext || window.webkitAudioContext)();
        _synthGain = _audioCtx.createGain();
        _synthGain.gain.value = _cfg.synthVolume;
        _synthGain.connect(_audioCtx.destination);
        _synthPlayer = new WebAudioFontPlayer();

        await _synthLoadInstrument(_cfg.instrumentIdx);
    } catch (e) {
        console.warn('[Piano] Synth init failed:', e);
    }
}

async function _synthLoadInstrument(idx) {
    const inst = INSTRUMENTS[idx];
    if (!inst || !_synthPlayer || !_audioCtx) return;
    _synthLoading = true;
    const varName = _wafVar(inst.gm);

    try {
        if (!window[varName]) {
            await _loadScript(_wafUrl(inst.gm));
        }
        const preset = window[varName];
        if (preset) {
            _synthPlayer.adjustPreset(_audioCtx, preset);
            _synthPreset = preset;
        }
    } catch (e) {
        console.warn('[Piano] Failed to load instrument:', inst.name, e);
    }
    _synthLoading = false;
}

function _synthEnsureCtx() {
    if (_audioCtx && _audioCtx.state === 'suspended') {
        _audioCtx.resume();
    }
}

function _synthNoteOn(midi, velocity) {
    if (!_synthPlayer || !_synthPreset || !_audioCtx || !_synthGain) return;
    _synthEnsureCtx();

    const existing = _noteEnvelopes.get(midi);
    if (existing) { try { existing.cancel(); } catch (_) {} }

    const vol = (velocity / 127) * _cfg.synthVolume;
    const envelope = _synthPlayer.queueWaveTable(
        _audioCtx, _synthGain, _synthPreset, 0, midi, 999, vol
    );
    _noteEnvelopes.set(midi, envelope);
}

function _synthNoteOff(midi) {
    const env = _noteEnvelopes.get(midi);
    if (env) {
        try { env.cancel(); } catch (_) {}
        _noteEnvelopes.delete(midi);
    }
}

function _synthReleaseAll() {
    for (const env of _noteEnvelopes.values()) {
        try { env.cancel(); } catch (_) {}
    }
    _noteEnvelopes.clear();
}

function _synthSetVolume(vol) {
    _saveCfg('synthVolume', vol);
    if (_synthGain) _synthGain.gain.value = vol;
}

// ═══════════════════════════════════════════════════════════════════════
// Web MIDI input
// ═══════════════════════════════════════════════════════════════════════

async function _midiInit() {
    if (_midiAccess) return;
    if (!navigator.requestMIDIAccess) return;
    try {
        _midiAccess = await navigator.requestMIDIAccess({ sysex: false });
        _midiAccess.onstatechange = () => _midiUpdateDeviceList();
        _midiAutoConnect();
    } catch (e) {
        console.warn('[Piano] MIDI access denied:', e);
    }
}

function _midiAutoConnect() {
    if (!_midiAccess) return;
    const inputs = [];
    _midiAccess.inputs.forEach(inp => inputs.push(inp));
    if (!inputs.length) return;

    // Distinguish "never picked a device" from "explicitly picked
    // None". localStorage.getItem returns null for the never-set
    // case and '' for an explicit-None save (via _midiConnect).
    // Read raw rather than _cfg.midiInputId, which collapses both
    // to '' via its `|| ''` default in the config initialiser.
    let raw = null;
    try { raw = localStorage.getItem(STORE_KEYS.midiInputId); } catch (_) {}
    if (raw === '') return;  // user opted out — respect it

    const target = inputs.find(i => i.id === raw) || inputs[0];
    _midiConnect(target.id);
}

function _midiConnect(id) {
    if (_midiInput) _midiInput.onmidimessage = null;
    _midiInput = null;

    // Persist the choice regardless of match. An empty id is the
    // "None" option and must be saved so _midiAutoConnect() on the
    // next init respects the opt-out instead of auto-picking
    // inputs[0] again. A non-empty id that doesn't match any
    // attached device also gets saved here — harmless, and lets a
    // re-plugged device reconnect to its saved slot without extra
    // UI work.
    _saveCfg('midiInputId', id || '');

    if (!id || !_midiAccess) {
        _midiUpdateDeviceList();
        return;
    }
    _midiAccess.inputs.forEach(inp => {
        if (inp.id === id) {
            _midiInput = inp;
            // Wire the handler only when the renderer is active.
            // If _midiInit's async chain resolves after destroy(),
            // we still CAPTURE the device so the next init's
            // _midiResumeHandler can re-wire without a second
            // _midiAutoConnect — we just don't listen right now.
            if (_midiActive) _midiInput.onmidimessage = _midiOnMessage;
        }
    });
    _midiUpdateDeviceList();
}

function _midiPauseHandler() {
    // Called from destroy() — detach the message handler so the
    // connected device stops firing _onNoteOn / _onNoteOff into a
    // plugin no longer visible. Keep the _midiInput reference so a
    // future init() can reattach without the user having to re-pick
    // their device in settings. Flipping _midiActive BEFORE the
    // detach also prevents a late-resolving _midiConnect (from an
    // in-flight _midiInit started in the most recent init()) from
    // re-wiring the handler on an already-destroyed renderer.
    _midiActive = false;
    if (_midiInput) _midiInput.onmidimessage = null;
}

function _midiResumeHandler() {
    // Called from init() — restore the handler if MIDI was already
    // connected in a previous piano lifetime. If _midiInput is null
    // this is a no-op; _midiInit + _midiAutoConnect will connect
    // afresh from settings. Flip _midiActive first so any in-flight
    // _midiConnect completing shortly after this returns wires the
    // handler too.
    _midiActive = true;
    if (_midiInput) _midiInput.onmidimessage = _midiOnMessage;
}

function _midiOnMessage(e) {
    const [status, note, velocity] = e.data;
    const ch = status & 0x0F;
    if (_cfg.midiChannel >= 0 && ch !== _cfg.midiChannel) return;

    const cmd = status & 0xF0;
    const transposed = note + _cfg.transpose;

    if (cmd === 0x90 && velocity > 0) {
        _onNoteOn(transposed, velocity);
    } else if (cmd === 0x80 || (cmd === 0x90 && velocity === 0)) {
        _onNoteOff(transposed);
    } else if (cmd === 0xB0 && note === 64) {
        if (velocity >= 64) {
            _sustainOn = true;
        } else {
            _sustainOn = false;
            for (const midi of _sustainedNotes) {
                _heldNotes.delete(midi);
                _synthNoteOff(midi);
            }
            _sustainedNotes.clear();
        }
    }
}

function _onNoteOn(midi, velocity) {
    if (midi < 0 || midi > 127) return;
    _heldNotes.set(midi, velocity);
    _synthNoteOn(midi, velocity);
    _synthEnsureCtx();
    if (_cfg.hitDetection) _checkHit(midi);
}

function _onNoteOff(midi) {
    if (midi < 0 || midi > 127) return;
    if (_sustainOn) {
        _sustainedNotes.add(midi);
        return;
    }
    _heldNotes.delete(midi);
    _synthNoteOff(midi);
}

function _midiUpdateDeviceList() {
    const sel = document.getElementById('piano-midi-select');
    if (!sel || !_midiAccess) return;

    const inputs = [];
    _midiAccess.inputs.forEach(inp => inputs.push(inp));

    // Build <option> elements via the DOM API rather than concatenating
    // an HTML string. MIDI device names come from the attached
    // hardware and can contain characters that would otherwise inject
    // markup (a maliciously-named device, or even an accidental "<"
    // in the vendor string) directly into the settings panel. Setting
    // .value and .textContent escapes both fields safely.
    sel.textContent = '';
    const noneOpt = document.createElement('option');
    noneOpt.value = '';
    noneOpt.textContent = 'None';
    sel.appendChild(noneOpt);
    for (const inp of inputs) {
        const opt = document.createElement('option');
        opt.value = inp.id;
        opt.textContent = inp.name;
        if (_midiInput && _midiInput.id === inp.id) opt.selected = true;
        sel.appendChild(opt);
    }
}

// ═══════════════════════════════════════════════════════════════════════
// Hit detection / accuracy scoring
// ═══════════════════════════════════════════════════════════════════════
//
// Score against the filtered chart the user is seeing — not the full
// unfiltered arrays — so the difficulty slider applies to hit detection
// too. draw() caches bundle.notes/chords/currentTime into _latest*
// every frame; async MIDI events read those snapshots.

function _checkHit(playedMidi) {
    const t = _latestTime;
    const notes = _latestNotes;
    const chords = _latestChords;

    let foundHit = false;

    if (notes) {
        for (const n of notes) {
            if (n.t > t + HIT_TOLERANCE + 0.5) break;
            if (n.t < t - HIT_TOLERANCE - 0.5) continue;
            const songMidi = noteToMidi(n.s, n.f);
            const key = _noteKey(n.t, songMidi);
            if (songMidi === playedMidi && Math.abs(n.t - t) <= HIT_TOLERANCE && !_hitNoteKeys.has(key)) {
                _hitNoteKeys.add(key);
                foundHit = true;
                break;
            }
        }
    }

    if (!foundHit && chords) {
        for (const c of chords) {
            if (c.t > t + HIT_TOLERANCE + 0.5) break;
            if (c.t < t - HIT_TOLERANCE - 0.5) continue;
            for (const cn of (c.notes || [])) {
                const songMidi = noteToMidi(cn.s, cn.f);
                const key = _noteKey(c.t, songMidi);
                if (songMidi === playedMidi && Math.abs(c.t - t) <= HIT_TOLERANCE && !_hitNoteKeys.has(key)) {
                    _hitNoteKeys.add(key);
                    foundHit = true;
                    break;
                }
            }
            if (foundHit) break;
        }
    }

    if (foundHit) {
        _hits++;
        _streak++;
        if (_streak > _bestStreak) _bestStreak = _streak;
    } else {
        _misses++;
        _streak = 0;
        _wrongFlashes.push({ midi: playedMidi, wall: performance.now() });
    }
}

function _updateMissedNotes(t, notes, chords) {
    if (!_cfg.hitDetection) return;
    const cutoff = t - HIT_TOLERANCE - 0.05;

    if (notes) {
        for (const n of notes) {
            if (n.t > cutoff) break;
            if (n.t < cutoff - 2) continue;
            const songMidi = noteToMidi(n.s, n.f);
            const key = _noteKey(n.t, songMidi);
            if (!_hitNoteKeys.has(key) && !_missedNoteKeys.has(key) && n.t < cutoff) {
                _missedNoteKeys.add(key);
            }
        }
    }
    if (chords) {
        for (const c of chords) {
            if (c.t > cutoff) break;
            if (c.t < cutoff - 2) continue;
            for (const cn of (c.notes || [])) {
                const songMidi = noteToMidi(cn.s, cn.f);
                const key = _noteKey(c.t, songMidi);
                if (!_hitNoteKeys.has(key) && !_missedNoteKeys.has(key) && c.t < cutoff) {
                    _missedNoteKeys.add(key);
                }
            }
        }
    }

    const now = performance.now();
    while (_wrongFlashes.length && now - _wrongFlashes[0].wall > 400) {
        _wrongFlashes.shift();
    }
}

function _resetScoring() {
    _hits = 0; _misses = 0; _streak = 0; _bestStreak = 0;
    _hitNoteKeys.clear();
    _missedNoteKeys.clear();
    _wrongFlashes.length = 0;
}

function _primeLatestSnapshot() {
    // Fill _latest* from highway's public getters so a MIDI note-on
    // that lands before the first draw() of a new chart still has a
    // snapshot to score against. These getters return the unfiltered
    // chart (difficulty slider applies to bundle.notes only), so the
    // first frame of scoring uses the full chart; subsequent frames
    // switch to filter-aware data. Worst case: one key-down immediately
    // after song:ready might score against a note the difficulty slider
    // has hidden — acceptable vs. guaranteeing the user a miss.
    try {
        if (typeof highway !== 'undefined') {
            _latestNotes = typeof highway.getNotes === 'function' ? highway.getNotes() : null;
            _latestChords = typeof highway.getChords === 'function' ? highway.getChords() : null;
            _latestTime = typeof highway.getTime === 'function' ? highway.getTime() : 0;
        }
    } catch (_) {
        _latestNotes = null;
        _latestChords = null;
        _latestTime = 0;
    }
}

// ═══════════════════════════════════════════════════════════════════════
// Note range detection
// ═══════════════════════════════════════════════════════════════════════

function detectRange(notes, chords) {
    let lo = 127, hi = 0;
    if (notes) {
        for (const n of notes) {
            const m = noteToMidi(n.s, n.f);
            if (m < lo) lo = m;
            if (m > hi) hi = m;
        }
    }
    if (chords) {
        for (const c of chords) {
            for (const cn of (c.notes || [])) {
                const m = noteToMidi(cn.s, cn.f);
                if (m < lo) lo = m;
                if (m > hi) hi = m;
            }
        }
    }
    if (lo > hi) { lo = 48; hi = 84; }
    lo = Math.max(0, Math.floor(lo / 12) * 12);
    hi = Math.min(127, Math.ceil((hi + 1) / 12) * 12 - 1);
    while (hi - lo < 47) { hi = Math.min(127, hi + 12); if (hi - lo < 47 && lo > 0) lo -= 12; }
    return { lo, hi };
}

function _visibleMidiRange(notes, chords, t) {
    let lo = 127, hi = 0;
    const tMax = t + VISIBLE_SECONDS;

    if (notes) {
        for (const n of notes) {
            const end = n.t + (n.sus || 0);
            if (end < t - 0.1) continue;
            if (n.t > tMax) break;
            const m = noteToMidi(n.s, n.f);
            if (m < lo) lo = m;
            if (m > hi) hi = m;
        }
    }
    if (chords) {
        for (const c of chords) {
            if (c.t < t - 0.1) continue;
            if (c.t > tMax) break;
            for (const cn of (c.notes || [])) {
                const m = noteToMidi(cn.s, cn.f);
                if (m < lo) lo = m;
                if (m > hi) hi = m;
            }
        }
    }
    return lo <= hi ? { lo, hi } : null;
}

function _updateDisplayRange(notes, chords, t) {
    const raw = _visibleMidiRange(notes, chords, t);
    if (!raw) {
        if (_displayLo !== null) return;
        const full = detectRange(notes, chords);
        _displayLo = full.lo;
        _displayHi = full.hi;
        return;
    }

    if (_displayLo !== null && raw.lo >= _displayLo && raw.hi <= _displayHi) {
        const loSlack = raw.lo - _displayLo;
        const hiSlack = _displayHi - raw.hi;
        if (loSlack < 12 && hiSlack < 12) return;
    }

    let lo = Math.max(0, raw.lo - 2);
    let hi = Math.min(127, raw.hi + 2);
    lo = Math.floor(lo / 12) * 12;
    hi = Math.ceil((hi + 1) / 12) * 12 - 1;
    while (hi - lo < 47) {
        if (lo > 0) lo -= 12; else hi = Math.min(127, hi + 12);
    }

    _displayLo = lo;
    _displayHi = hi;
}

// ═══════════════════════════════════════════════════════════════════════
// Settings panel + gear button
// ═══════════════════════════════════════════════════════════════════════

function _injectSettingsGear() {
    const controls = document.getElementById('player-controls');
    if (!controls || _settingsGear) return;

    const closeBtn = controls.querySelector('button:last-child');
    const gear = document.createElement('button');
    gear.id = 'btn-piano-settings';
    gear.className = 'px-2 py-1.5 bg-dark-600 hover:bg-dark-500 rounded-lg text-xs text-gray-400 transition';
    gear.type = 'button';
    gear.title = 'Piano settings (MIDI, sound, scoring)';
    // Accessible name for screen readers — title alone is announced
    // inconsistently across readers, and the glyph itself would
    // otherwise surface as "black gear" or similar ambiguous text.
    gear.setAttribute('aria-label', 'Piano settings');
    // Build the glyph in a span marked aria-hidden so the accessible
    // name above stays the authoritative label and the decorative
    // symbol isn't announced twice.
    const glyph = document.createElement('span');
    glyph.setAttribute('aria-hidden', 'true');
    glyph.textContent = '⚙';
    gear.appendChild(glyph);
    gear.onclick = _toggleSettings;
    controls.insertBefore(gear, closeBtn);
    _settingsGear = gear;
}

function _removeSettingsGear() {
    if (_settingsGear) {
        _settingsGear.remove();
        _settingsGear = null;
    }
}

function _toggleSettings() {
    _settingsVisible = !_settingsVisible;
    if (!_settingsPanel && _settingsVisible) _createSettingsPanel();
    if (_settingsPanel) _settingsPanel.style.display = _settingsVisible ? '' : 'none';
    if (_settingsVisible) {
        _midiInit();
        _synthInit();
        _midiUpdateDeviceList();
    }
}

function _createSettingsPanel() {
    if (_settingsPanel) return;
    const player = document.getElementById('player');
    if (!player) return;

    const panel = document.createElement('div');
    panel.id = 'piano-settings-panel';
    panel.style.cssText = 'position:absolute;top:0;left:0;right:0;z-index:25;' +
        'background:rgba(8,8,20,0.94);border-bottom:1px solid #222;padding:6px 12px;' +
        'font-family:system-ui,sans-serif;display:none;';

    const channelOpts = '<option value="-1"' + (_cfg.midiChannel === -1 ? ' selected' : '') + '>All</option>' +
        Array.from({length: 16}, (_, i) =>
            `<option value="${i}"${_cfg.midiChannel === i ? ' selected' : ''}>${i + 1}</option>`
        ).join('');

    const instrumentOpts = INSTRUMENTS.map((inst, i) =>
        `<option value="${i}"${_cfg.instrumentIdx === i ? ' selected' : ''}>${inst.name}</option>`
    ).join('');

    panel.innerHTML = `
        <div style="display:flex;gap:14px;align-items:center;flex-wrap:wrap;">
            <div style="display:flex;align-items:center;gap:4px;">
                <span style="font-size:10px;color:#666;">MIDI</span>
                <select id="piano-midi-select" style="background:#1a1a2e;border:1px solid #333;border-radius:6px;
                    padding:3px 6px;font-size:11px;color:#ccc;outline:none;max-width:180px;">
                    <option value="">None</option>
                </select>
            </div>
            <div style="display:flex;align-items:center;gap:4px;">
                <span style="font-size:10px;color:#666;">Sound</span>
                <select id="piano-instrument-select" style="background:#1a1a2e;border:1px solid #333;border-radius:6px;
                    padding:3px 6px;font-size:11px;color:#ccc;outline:none;">
                    ${instrumentOpts}
                </select>
            </div>
            <div style="display:flex;align-items:center;gap:4px;">
                <span style="font-size:10px;color:#666;">Vol</span>
                <input type="range" id="piano-vol-slider" min="0" max="100"
                    value="${Math.round(_cfg.synthVolume * 100)}"
                    style="width:70px;accent-color:#6366f1;height:14px;">
            </div>
            <div style="display:flex;align-items:center;gap:4px;">
                <span style="font-size:10px;color:#666;">Ch</span>
                <select id="piano-channel-select" style="background:#1a1a2e;border:1px solid #333;border-radius:6px;
                    padding:3px 6px;font-size:11px;color:#ccc;outline:none;width:52px;">
                    ${channelOpts}
                </select>
            </div>
            <div style="display:flex;align-items:center;gap:3px;">
                <span style="font-size:10px;color:#666;">Transpose</span>
                <button id="piano-tr-down" style="background:#1a1a2e;border:1px solid #333;border-radius:4px;
                    width:20px;height:20px;color:#aaa;font-size:12px;cursor:pointer;line-height:1;">-</button>
                <span id="piano-tr-val" style="font-size:11px;color:#ccc;min-width:18px;text-align:center;">${_cfg.transpose}</span>
                <button id="piano-tr-up" style="background:#1a1a2e;border:1px solid #333;border-radius:4px;
                    width:20px;height:20px;color:#aaa;font-size:12px;cursor:pointer;line-height:1;">+</button>
            </div>
            <label style="display:flex;align-items:center;gap:3px;font-size:11px;color:#999;cursor:pointer;">
                <input type="checkbox" id="piano-chk-names" ${_cfg.showNoteNames ? 'checked' : ''}
                    style="accent-color:#6366f1;"> Notes
            </label>
            <label style="display:flex;align-items:center;gap:3px;font-size:11px;color:#999;cursor:pointer;">
                <input type="checkbox" id="piano-chk-hits" ${_cfg.hitDetection ? 'checked' : ''}
                    style="accent-color:#22cc66;"> Hits
            </label>
        </div>`;

    const controls = document.getElementById('player-controls');
    if (controls) {
        player.insertBefore(panel, controls);
    } else {
        player.appendChild(panel);
    }
    _settingsPanel = panel;

    panel.querySelector('#piano-midi-select').onchange = function () {
        _midiConnect(this.value);
        _synthInit();
    };
    panel.querySelector('#piano-instrument-select').onchange = async function () {
        const idx = parseInt(this.value);
        _saveCfg('instrumentIdx', idx);
        await _synthInit();
        await _synthLoadInstrument(idx);
    };
    panel.querySelector('#piano-vol-slider').oninput = function () {
        _synthSetVolume(parseInt(this.value) / 100);
    };
    panel.querySelector('#piano-channel-select').onchange = function () {
        _saveCfg('midiChannel', parseInt(this.value));
    };
    panel.querySelector('#piano-tr-down').onclick = function () {
        const v = Math.max(-12, _cfg.transpose - 1);
        _saveCfg('transpose', v);
        document.getElementById('piano-tr-val').textContent = v;
    };
    panel.querySelector('#piano-tr-up').onclick = function () {
        const v = Math.min(12, _cfg.transpose + 1);
        _saveCfg('transpose', v);
        document.getElementById('piano-tr-val').textContent = v;
    };
    panel.querySelector('#piano-chk-names').onchange = function () {
        _saveCfg('showNoteNames', this.checked);
    };
    panel.querySelector('#piano-chk-hits').onchange = function () {
        _saveCfg('hitDetection', this.checked);
        if (this.checked) _resetScoring();
    };
}

function _removeSettingsPanel() {
    if (_settingsPanel) {
        _settingsPanel.remove();
        _settingsPanel = null;
    }
    _settingsVisible = false;
}

// ═══════════════════════════════════════════════════════════════════════
// Keyboard geometry
// ═══════════════════════════════════════════════════════════════════════

function buildKeyLayout(lo, hi, areaX, areaW) {
    const keys = [];
    let whiteCount = 0;
    for (let m = lo; m <= hi; m++) {
        if (!isBlackKey(m)) whiteCount++;
    }
    if (whiteCount === 0) return keys;

    const whiteW = areaW / whiteCount;
    const blackW = whiteW * 0.6;

    let wx = areaX;
    for (let m = lo; m <= hi; m++) {
        if (!isBlackKey(m)) {
            keys.push({ midi: m, x: wx, w: whiteW, black: false });
            wx += whiteW;
        }
    }
    for (let m = lo; m <= hi; m++) {
        if (!isBlackKey(m)) continue;
        const prevWhite = keys.find(k => !k.black && k.midi === m - 1);
        if (prevWhite) {
            keys.push({ midi: m, x: prevWhite.x + prevWhite.w - blackW / 2, w: blackW, black: true });
        }
    }
    return keys;
}

function keyForMidi(midi, layout) {
    for (const k of layout) {
        if (k.midi === midi) return k;
    }
    return null;
}

// ═══════════════════════════════════════════════════════════════════════
// Drawing
// ═══════════════════════════════════════════════════════════════════════

function _draw(notes, chords, t, beats) {
    if (!_pianoCanvas || !_pianoCtx) return;

    // Update the MIDI-scoring snapshots FIRST — before the
    // no-chart-yet early return below. If a song change arrives
    // with bundle.currentTime advancing but notes/chords still
    // empty (WS reconnect window), an async MIDI key-down between
    // frames would otherwise score against the PREVIOUS song's
    // cached chart and its old t. Clearing here resets both the
    // arrays and the time reference so _checkHit sees an empty
    // chart and scores the stray press as a miss without timing
    // it against stale data.
    _latestNotes = notes;
    _latestChords = chords;
    _latestTime = t;

    if (!notes && !chords) return;

    const W = _pianoCanvas.width / (window.devicePixelRatio || 1);
    const H = _pianoCanvas.height / (window.devicePixelRatio || 1);
    const ctx = _pianoCtx;

    _updateDisplayRange(notes, chords, t);
    if (_displayLo === null) return;
    const lo = _displayLo;
    const hi = _displayHi;

    const kbH = H * KEYBOARD_H_FRAC;
    const kbTop = H - kbH;
    const padL = 10, padR = 10;

    if (!_cachedLayout || _lastLayoutW !== W || lo !== _lastRangeLo || hi !== _lastRangeHi) {
        _cachedLayout = buildKeyLayout(lo, hi, padL, W - padL - padR);
        _lastLayoutW = W;
        _lastRangeLo = lo;
        _lastRangeHi = hi;
    }
    const layout = _cachedLayout;

    _updateMissedNotes(t, notes, chords);

    // ── Background ──────────────────────────────────────────────────
    ctx.fillStyle = '#040408';
    ctx.fillRect(0, 0, W, H);

    // ── Vertical key-aligned grid lines ─────────────────────────────
    const noteAreaTop = 0;
    const nowLineY = kbTop * NOW_LINE_Y_FRAC;

    for (const k of layout) {
        if (k.black) continue;
        const isC = k.midi % 12 === 0;
        ctx.strokeStyle = isC ? 'rgba(255,255,255,0.08)' : 'rgba(255,255,255,0.04)';
        ctx.lineWidth = isC ? 1.5 : 0.5;
        ctx.beginPath();
        ctx.moveTo(k.x + k.w - 0.5, noteAreaTop);
        ctx.lineTo(k.x + k.w - 0.5, kbTop);
        ctx.stroke();
    }

    // ── Beat / measure lines ────────────────────────────────────────
    if (beats) {
        for (const b of beats) {
            const dt = b.time - t;
            if (dt < -0.1 || dt > VISIBLE_SECONDS) continue;
            const y = _timeToY(dt, nowLineY, noteAreaTop);
            ctx.strokeStyle = b.measure > 0 ? 'rgba(255,255,255,0.12)' : 'rgba(255,255,255,0.04)';
            ctx.lineWidth = b.measure > 0 ? 1.5 : 0.5;
            ctx.beginPath();
            ctx.moveTo(padL, y);
            ctx.lineTo(W - padR, y);
            ctx.stroke();
        }
    }

    // ── Now line ────────────────────────────────────────────────────
    ctx.strokeStyle = 'rgba(255,255,255,0.4)';
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    ctx.moveTo(padL, nowLineY);
    ctx.lineTo(W - padR, nowLineY);
    ctx.stroke();

    _drawScrollingNotes(ctx, notes, chords, t, layout, noteAreaTop, nowLineY);
    _drawKeyboard(ctx, layout, kbTop, kbH, notes, chords, t);

    if (_cfg.hitDetection && (_hits + _misses) > 0) {
        _drawAccuracyHUD(ctx, W);
    }

    if (_midiInput) {
        ctx.fillStyle = '#22cc66';
        ctx.beginPath();
        ctx.arc(W - 20, 16, 4, 0, Math.PI * 2);
        ctx.fill();
        ctx.fillStyle = '#22cc6688';
        ctx.font = '9px sans-serif';
        ctx.textAlign = 'right';
        ctx.textBaseline = 'middle';
        ctx.fillText('MIDI', W - 28, 16);
    }
}

function _timeToY(dt, nowLineY, topY) {
    if (dt <= 0) return nowLineY + (-dt / 0.3) * 20;
    const frac = dt / VISIBLE_SECONDS;
    return nowLineY - frac * (nowLineY - topY);
}

function _drawScrollingNotes(ctx, notes, chords, t, layout, topY, nowLineY) {
    const allNotes = [];

    if (notes) {
        for (const n of notes) {
            const dt = n.t - t;
            if (dt > VISIBLE_SECONDS + 1) break;
            if (dt < -1 && (n.t + (n.sus || 0)) < t - 0.5) continue;
            allNotes.push({ midi: noteToMidi(n.s, n.f), t: n.t, sus: n.sus || 0, accent: n.ac });
        }
    }
    if (chords) {
        for (const c of chords) {
            const dt = c.t - t;
            if (dt > VISIBLE_SECONDS + 1) break;
            if (dt < -1) continue;
            for (const cn of (c.notes || [])) {
                allNotes.push({ midi: noteToMidi(cn.s, cn.f), t: c.t, sus: cn.sus || 0, accent: cn.ac });
            }
        }
    }

    for (const n of allNotes) {
        const key = keyForMidi(n.midi, layout);
        if (!key) continue;

        const dt = n.t - t;
        const dtEnd = (n.t + n.sus) - t;

        const yBottom = _timeToY(dt, nowLineY, topY);
        const yTop = n.sus > 0.05 ? _timeToY(Math.max(dt, dtEnd), nowLineY, topY) : yBottom - 8;

        const y1 = Math.max(topY, Math.min(yTop, yBottom));
        const y2 = Math.min(nowLineY + 10, Math.max(yTop, yBottom));
        const noteH = y2 - y1;
        if (noteH < 1) continue;

        const isActive = dt <= 0.05 && dtEnd >= -0.05;
        const isOnBlack = key.black;

        const inset = isOnBlack ? 1 : 2;
        const barX = key.x + inset;
        const barW = key.w - inset * 2;
        const radius = Math.min(4, barW / 3, noteH / 2);

        const nk = _noteKey(n.t, n.midi);
        let useHitColor = false, useMissColor = false;
        if (_cfg.hitDetection) {
            if (_hitNoteKeys.has(nk)) useHitColor = true;
            else if (_missedNoteKeys.has(nk)) useMissColor = true;
        }

        const [cr, cg, cb] = _neonRGB(n.midi);
        const df = isOnBlack ? 0.7 : 1.0;
        let r = cr * df, g = cg * df, b = cb * df;

        if (useHitColor) { r = 0; g = 1; b = 0.27; }
        else if (useMissColor) { r = 0.33; g = 0.33; b = 0.4; }

        if (!useMissColor) {
            const glowAlpha = isActive ? 0.5 : 0.25;
            for (let i = 2; i >= 0; i--) {
                const spread = (i + 1) * 2;
                const a = glowAlpha * (0.15 + (2 - i) * 0.12);
                ctx.strokeStyle = _rgbStr(r, g, b, a);
                ctx.lineWidth = spread;
                _roundRect(ctx, barX - 1, y1 - 1, barW + 2, noteH + 2, radius + 1);
                ctx.stroke();
            }
        }

        ctx.fillStyle = _rgbStr(r, g, b, useMissColor ? 0.4 : 1);
        _roundRect(ctx, barX, y1, barW, noteH, radius);
        ctx.fill();

        if (!useMissColor && noteH > 4) {
            const grad = ctx.createLinearGradient(0, y1, 0, y1 + Math.min(noteH, 12));
            grad.addColorStop(0, _rgbStr(Math.min(r + 0.3, 1), Math.min(g + 0.3, 1), Math.min(b + 0.3, 1), 0.4));
            grad.addColorStop(1, 'rgba(0,0,0,0)');
            ctx.fillStyle = grad;
            _roundRect(ctx, barX, y1, barW, noteH, radius);
            ctx.fill();
        }

        if (_cfg.showNoteNames && noteH >= NOTE_LABEL_MIN_H && barW >= 14) {
            const fontSize = Math.min(10, barW * 0.45);
            ctx.font = `bold ${fontSize}px sans-serif`;
            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';
            ctx.fillStyle = 'rgba(0,0,0,0.6)';
            ctx.fillText(midiToNoteName(n.midi), barX + barW / 2 + 0.5, y1 + noteH / 2 + 0.5);
            ctx.fillStyle = '#fff';
            ctx.fillText(midiToNoteName(n.midi), barX + barW / 2, y1 + noteH / 2);
        }
    }
}

function _approachAlpha(midi, notes, chords, t) {
    const lookAhead = VISIBLE_SECONDS * 0.6;
    let closest = Infinity;
    if (notes) {
        for (const n of notes) {
            if (n.t < t - 0.05) continue;
            if (n.t > t + lookAhead) break;
            if (noteToMidi(n.s, n.f) === midi) {
                closest = Math.min(closest, n.t - t);
            }
        }
    }
    if (chords) {
        for (const c of chords) {
            if (c.t < t - 0.05) continue;
            if (c.t > t + lookAhead) break;
            for (const cn of (c.notes || [])) {
                if (noteToMidi(cn.s, cn.f) === midi) {
                    closest = Math.min(closest, c.t - t);
                }
            }
        }
    }
    if (closest === Infinity) return 0;
    return Math.max(0, 1 - closest / lookAhead);
}

function _drawKeyboard(ctx, layout, kbTop, kbH, notes, chords, t) {
    const songActiveSet = new Set();
    const window_ = 0.06;
    if (notes) {
        for (const n of notes) {
            if (n.t > t + window_) continue;
            const end = n.t + (n.sus || 0);
            if (end < t - window_) continue;
            if (n.t <= t + window_ && end >= t - window_)
                songActiveSet.add(noteToMidi(n.s, n.f));
        }
    }
    if (chords) {
        for (const c of chords) {
            if (c.t > t + window_) continue;
            if (c.t < t - 1) continue;
            for (const cn of (c.notes || [])) {
                const end = c.t + (cn.sus || 0);
                if (c.t <= t + window_ && end >= t - window_)
                    songActiveSet.add(noteToMidi(cn.s, cn.f));
            }
        }
    }

    const wrongSet = new Set();
    const now = performance.now();
    for (const wf of _wrongFlashes) {
        if (now - wf.wall < 400) wrongSet.add(wf.midi);
    }

    ctx.fillStyle = '#060610';
    ctx.fillRect(0, kbTop - 1, ctx.canvas.width / (window.devicePixelRatio || 1), kbH + 3);

    const blackH = kbH * 0.62;
    const cornerR = 5;

    for (const k of layout) {
        if (k.black) continue;
        const songActive = songActiveSet.has(k.midi);
        const playerHeld = _heldNotes.has(k.midi);
        const isWrong = wrongSet.has(k.midi);
        const pressed = songActive || playerHeld;
        const pressOffset = pressed ? 2 : 0;
        const kw = k.w - 1;

        const [nr, ng, nb] = _neonRGB(k.midi);
        let fr = 0.91, fg = 0.91, fb = 0.94;
        if (playerHeld && songActive) {
            fr = 0; fg = 1; fb = 0.27;
        } else if (isWrong && playerHeld) {
            fr = 1; fg = 0.27; fb = 0.27;
        } else if (playerHeld) {
            fr = 0.27; fg = 0.53; fb = 1;
        } else if (songActive) {
            fr = nr; fg = ng; fb = nb;
        } else {
            const ap = _approachAlpha(k.midi, notes, chords, t);
            if (ap > 0) {
                fr += (nr - fr) * ap * 0.6;
                fg += (ng - fg) * ap * 0.6;
                fb += (nb - fb) * ap * 0.6;
            }
        }

        const grad = ctx.createLinearGradient(0, kbTop + pressOffset, 0, kbTop + kbH);
        grad.addColorStop(0, _rgbStr(Math.min(fr + 0.08, 1), Math.min(fg + 0.08, 1), Math.min(fb + 0.08, 1)));
        grad.addColorStop(0.85, _rgbStr(fr, fg, fb));
        grad.addColorStop(1, _rgbStr(fr * 0.75, fg * 0.75, fb * 0.75));
        ctx.fillStyle = grad;
        _roundRectBottom(ctx, k.x, kbTop + pressOffset, kw, kbH - pressOffset, cornerR);
        ctx.fill();

        ctx.strokeStyle = 'rgba(100,100,120,0.4)';
        ctx.lineWidth = 0.5;
        _roundRectBottom(ctx, k.x, kbTop + pressOffset, kw, kbH - pressOffset, cornerR);
        ctx.stroke();

        if (!pressed) {
            const ap = _approachAlpha(k.midi, notes, chords, t);
            if (ap > 0.15) {
                const ba = Math.min((ap - 0.15) * 1.5, 1);
                ctx.strokeStyle = _rgbStr(nr, ng, nb, ba * 0.6);
                ctx.lineWidth = 2;
                _roundRectBottom(ctx, k.x + 1, kbTop + 1, kw - 2, kbH - 2, cornerR);
                ctx.stroke();
            }
        }

        if (pressed) {
            ctx.shadowColor = _rgbStr(fr, fg, fb);
            ctx.shadowBlur = 12;
            ctx.fillStyle = 'rgba(0,0,0,0)';
            _roundRectBottom(ctx, k.x, kbTop + pressOffset, kw, kbH - pressOffset, cornerR);
            ctx.fill();
            ctx.shadowBlur = 0;
        }

        const pc = k.midi % 12;
        const noteLetter = ['C','','D','','E','F','','G','','A','','B'][pc];
        if (noteLetter) {
            const isC = pc === 0;
            const label = isC ? 'C' + (Math.floor(k.midi / 12) - 1) : noteLetter;
            ctx.fillStyle = pressed ? 'rgba(0,0,0,0.7)' : 'rgba(80,80,100,0.5)';
            ctx.font = `${isC ? 'bold ' : ''}${Math.min(10, kw * 0.45)}px sans-serif`;
            ctx.textAlign = 'center';
            ctx.textBaseline = 'bottom';
            ctx.fillText(label, k.x + kw / 2, kbTop + kbH - 3 + pressOffset);
        }
    }

    for (const k of layout) {
        if (!k.black) continue;
        const songActive = songActiveSet.has(k.midi);
        const playerHeld = _heldNotes.has(k.midi);
        const isWrong = wrongSet.has(k.midi);
        const pressed = songActive || playerHeld;
        const pressOffset = pressed ? 1 : 0;

        const [nr, ng, nb] = _neonRGB(k.midi);
        let fr = 0.1, fg = 0.1, fb = 0.12;
        if (playerHeld && songActive) {
            fr = 0; fg = 0.8; fb = 0.2;
        } else if (isWrong && playerHeld) {
            fr = 0.8; fg = 0.15; fb = 0.15;
        } else if (playerHeld) {
            fr = 0.2; fg = 0.4; fb = 0.8;
        } else if (songActive) {
            fr = nr * 0.8; fg = ng * 0.8; fb = nb * 0.8;
        } else {
            const ap = _approachAlpha(k.midi, notes, chords, t);
            if (ap > 0) {
                fr += (nr * 0.7 - fr) * ap * 0.6;
                fg += (ng * 0.7 - fg) * ap * 0.6;
                fb += (nb * 0.7 - fb) * ap * 0.6;
            }
        }

        const grad = ctx.createLinearGradient(0, kbTop + pressOffset, 0, kbTop + blackH);
        grad.addColorStop(0, _rgbStr(Math.min(fr + 0.06, 1), Math.min(fg + 0.06, 1), Math.min(fb + 0.06, 1)));
        grad.addColorStop(0.7, _rgbStr(fr, fg, fb));
        grad.addColorStop(1, _rgbStr(fr * 0.6, fg * 0.6, fb * 0.6));
        ctx.fillStyle = grad;
        _roundRectBottom(ctx, k.x, kbTop + pressOffset, k.w, blackH - pressOffset, 3);
        ctx.fill();

        ctx.strokeStyle = 'rgba(50,50,60,0.5)';
        ctx.lineWidth = 0.5;
        _roundRectBottom(ctx, k.x, kbTop + pressOffset, k.w, blackH - pressOffset, 3);
        ctx.stroke();

        if (!pressed) {
            const ap = _approachAlpha(k.midi, notes, chords, t);
            if (ap > 0.15) {
                const ba = Math.min((ap - 0.15) * 1.5, 1);
                ctx.strokeStyle = _rgbStr(nr, ng, nb, ba * 0.5);
                ctx.lineWidth = 1.5;
                _roundRectBottom(ctx, k.x + 1, kbTop + 1, k.w - 2, blackH - 2, 3);
                ctx.stroke();
            }
        }

        if (pressed) {
            ctx.shadowColor = _rgbStr(fr, fg, fb);
            ctx.shadowBlur = 10;
            ctx.fillStyle = 'rgba(0,0,0,0)';
            _roundRectBottom(ctx, k.x, kbTop + pressOffset, k.w, blackH - pressOffset, 3);
            ctx.fill();
            ctx.shadowBlur = 0;
        }
    }
}

function _drawAccuracyHUD(ctx, W) {
    const total = _hits + _misses;
    const pct = total > 0 ? Math.round((_hits / total) * 100) : 0;

    const hudY = 10;
    const hudH = 22;
    const text = `Accuracy: ${pct}%   Streak: ${_streak}   Best: ${_bestStreak}   ${_hits}/${total}`;

    ctx.font = 'bold 11px sans-serif';
    const tw = ctx.measureText(text).width;
    const hudX = (W - tw) / 2 - 12;
    const hudW = tw + 24;

    ctx.fillStyle = 'rgba(8,8,20,0.75)';
    _roundRect(ctx, hudX, hudY, hudW, hudH, 6);
    ctx.fill();

    ctx.fillStyle = pct >= 80 ? '#22cc66' : pct >= 50 ? '#ffcc33' : '#ff6644';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(text, W / 2, hudY + hudH / 2);
}

function _roundRect(ctx, x, y, w, h, r) {
    r = Math.min(r, w / 2, h / 2);
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.lineTo(x + w - r, y);
    ctx.quadraticCurveTo(x + w, y, x + w, y + r);
    ctx.lineTo(x + w, y + h - r);
    ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
    ctx.lineTo(x + r, y + h);
    ctx.quadraticCurveTo(x, y + h, x, y + h - r);
    ctx.lineTo(x, y + r);
    ctx.quadraticCurveTo(x, y, x + r, y);
    ctx.closePath();
}

function _roundRectBottom(ctx, x, y, w, h, r) {
    r = Math.min(r, w / 2, h / 2);
    ctx.beginPath();
    ctx.moveTo(x, y);
    ctx.lineTo(x + w, y);
    ctx.lineTo(x + w, y + h - r);
    ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
    ctx.lineTo(x + r, y + h);
    ctx.quadraticCurveTo(x, y + h, x, y + h - r);
    ctx.closePath();
}

// ═══════════════════════════════════════════════════════════════════════
// Lifecycle helpers
// ═══════════════════════════════════════════════════════════════════════

function _createOverlayCanvas() {
    const player = document.getElementById('player');
    if (!player) return null;

    const canvas = document.createElement('canvas');
    canvas.id = 'piano-highway-canvas';
    canvas.style.cssText = 'position:absolute;top:0;left:0;width:100%;height:100%;z-index:5;pointer-events:none;';

    const controls = document.getElementById('player-controls');
    if (controls) {
        player.insertBefore(canvas, controls);
        // Keep controls above the overlay so the toggle gear stays clickable.
        controls.style.position = 'relative';
        controls.style.zIndex = '20';
    } else {
        player.appendChild(canvas);
    }
    return canvas;
}

function _applyCanvasDims(canvas) {
    // Always re-measure #player in CSS pixels rather than use the w/h
    // that highway.js passes to resize(). Those are backing-store dims
    // scaled by `_renderScale` (HD/Medium/Low), tuned for the 2D or
    // WebGL renderer that OWNS the given canvas. The piano runs on its
    // OWN overlay canvas sized to the FULL #player region (the canvas
    // style above is width:100%; height:100%; position:absolute, so
    // it stretches to cover the entire container). The controls strip
    // stays clickable because #player-controls is layered above the
    // overlay via z-index — it isn't subtracted from the canvas size.
    // Source of truth is therefore the player element's rect, not the
    // highway canvas's backing store.
    if (!canvas) return;
    const player = document.getElementById('player');
    if (!player) return;
    const w = player.clientWidth;
    const h = player.clientHeight;
    if (!w || !h) return;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = w * dpr;
    canvas.height = h * dpr;
    canvas.style.width = w + 'px';
    canvas.style.height = h + 'px';
    if (_pianoCtx) _pianoCtx.setTransform(dpr, 0, 0, dpr, 0, 0);
}

// ═══════════════════════════════════════════════════════════════════════
// Factory — slopsmith#36 setRenderer contract
// ═══════════════════════════════════════════════════════════════════════

function createFactory() {
    let _isReady = false;
    // Per-instance listeners so destroy() can remove the exact
    // function references (anonymous arrows aren't removable).
    const _onWinResize = () => _applyCanvasDims(_pianoCanvas);
    const _onSongReady = () => _resetForNewChart();

    // Called from the song:ready listener wired below and from init()
    // itself. Wipes scoring, cached layout, and the piano's display
    // range so the next chart/arrangement doesn't inherit stale state.
    // Critical for Auto-mode Keys-to-Keys transitions (piano renderer
    // stays selected across the arrangement switch).
    function _resetForNewChart() {
        _resetScoring();
        _cachedLayout = null;
        _lastLayoutW = 0;
        _lastRangeLo = -1;
        _lastRangeHi = -1;
        _displayLo = null;
        _displayHi = null;
        // Pull current arrays so a MIDI note-on arriving before the
        // next draw() has something recent to score against.
        _primeLatestSnapshot();
    }

    return {
        init(canvas /* , bundle */) {
            // Defensive teardown in case a prior init wasn't paired
            // with destroy (shouldn't happen per the contract, but
            // survive a misbehaving caller). Mirror destroy()'s
            // cleanup exactly — including restoreCanvas=true. If we
            // skipped the restore, the prior lifetime's highway
            // canvas would stay `display:none` going into the fresh
            // capture below, poisoning `_prevHighwayDisplay` with
            // "none" so a later destroy() would re-hide the canvas
            // permanently. Also: just dropping _pianoCanvas without
            // removing the window / slopsmith listeners or pausing
            // MIDI would leak duplicate subscriptions on every
            // re-init.
            if (_pianoCanvas || _isReady) {
                window.removeEventListener('resize', _onWinResize);
                if (window.slopsmith) window.slopsmith.off?.('song:ready', _onSongReady);
                _midiPauseHandler();
                _teardown(/* restoreCanvas */ true);
                _isReady = false;
            }

            _highwayCanvas = canvas;
            _prevHighwayDisplay = canvas ? canvas.style.display : '';

            _pianoCanvas = _createOverlayCanvas();
            if (!_pianoCanvas) {
                // #player not in DOM — leave the 2D highway visible
                // so the user isn't stuck on a blank viz. destroy()
                // still no-op-cleans.
                console.warn('[Piano] init: #player container missing; aborting');
                return;
            }
            _pianoCtx = _pianoCanvas.getContext('2d');
            if (!_pianoCtx) {
                // 2D context unavailable (browser policy / OOM / a
                // stale canvas that somehow lived through a previous
                // WebGL acquire). Tear down our freshly-built overlay
                // and leave the highway canvas visible as a fallback;
                // without this guard we'd have hidden the highway
                // below and every draw() would silently no-op against
                // a null ctx, leaving a blank player.
                console.warn('[Piano] init: getContext("2d") returned null; aborting');
                _pianoCanvas.remove();
                _pianoCanvas = null;
                _highwayCanvas = null;
                _prevHighwayDisplay = '';
                return;
            }

            // Only hide the 2D highway once our overlay is ready —
            // if overlay creation had failed we'd want the default
            // visible as a fallback.
            if (_highwayCanvas) _highwayCanvas.style.display = 'none';

            _injectSettingsGear();
            _applyCanvasDims(_pianoCanvas);
            window.addEventListener('resize', _onWinResize);
            // Optional-chain .on as well as the receiver: older
            // slopsmith cores (pre-Wave A) expose window.slopsmith as
            // a plain object without the on/off bus, and a bare
            // .on(...) call there would throw. With the optional
            // chain this degrades to a no-op on those cores.
            window.slopsmith?.on?.('song:ready', _onSongReady);

            _resetForNewChart();

            // Kick off MIDI + synth in the background. These are
            // one-time initialisations — a subsequent init() on a
            // fresh factory instance will no-op because _midiAccess
            // / _synthPlayer are already populated.
            _midiInit();
            _synthInit();
            // Reattach the MIDI handler if a prior piano lifetime
            // paused it on destroy. Safe no-op when no device is
            // connected yet — _midiInit's autoconnect will wire
            // things up once access resolves.
            _midiResumeHandler();

            _isReady = true;
        },
        draw(bundle) {
            if (!_isReady || !bundle) return;
            _draw(bundle.notes, bundle.chords, bundle.currentTime, bundle.beats);
        },
        resize(/* w, h */) {
            // highway.js hands us canvas.width / canvas.height — the
            // #highway backing store dimensions scaled by _renderScale.
            // Those are tuned for the renderer that owns that canvas;
            // our overlay canvas covers the whole #player region, so
            // re-measure from the element rect instead of trusting the
            // passed dims.
            if (!_isReady) return;
            _applyCanvasDims(_pianoCanvas);
        },
        destroy() {
            _isReady = false;
            window.removeEventListener('resize', _onWinResize);
            if (window.slopsmith) window.slopsmith.off?.('song:ready', _onSongReady);
            _midiPauseHandler();
            _teardown(/* restoreCanvas */ true);
        },
    };

    function _teardown(restoreCanvas) {
        if (_pianoCanvas) {
            _pianoCanvas.remove();
            _pianoCanvas = null;
            _pianoCtx = null;
        }
        _removeSettingsPanel();
        _removeSettingsGear();

        // Release any sounding notes so the user doesn't get a hung
        // tone when switching viz mid-song.
        _synthReleaseAll();
        _heldNotes.clear();
        _sustainedNotes.clear();
        _sustainOn = false;

        if (restoreCanvas && _highwayCanvas) {
            _highwayCanvas.style.display = _prevHighwayDisplay;
            _highwayCanvas = null;
            _prevHighwayDisplay = '';
        }

        _latestNotes = null;
        _latestChords = null;
        _latestTime = 0;
    }
}

createFactory.matchesArrangement = function (songInfo) {
    if (!songInfo) return false;
    if (songInfo.arrangement && KEYS_PATTERNS.test(songInfo.arrangement)) return true;
    if (Array.isArray(songInfo.arrangements)) {
        const idx = songInfo.arrangement_index;
        const arr = songInfo.arrangements.find(a => a.index === idx);
        if (arr && KEYS_PATTERNS.test(arr.name)) return true;
    }
    return false;
};

window.slopsmithViz_piano = createFactory;

})();
